// UK lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : '引用',
abbr_desc : '略語',
acronym_desc : '略語(頭文字)',
del_desc : '削除',
ins_desc : '挿入',
attribute_label_title : 'タイトル',
attribute_label_id : 'ID',
attribute_label_class : 'クラス',
attribute_label_style : 'スタイル',
attribute_label_cite : 'コメント',
attribute_label_datetime : '日時',
attribute_label_langdir : 'テキスト方向',
attribute_option_ltr : '左から右',
attribute_option_rtl : '右から左',
attribute_label_langcode : 'ランゲージ',
attribute_label_tabindex : 'TabIndex',
attribute_label_accesskey : 'アクセスキー',
attribute_label_cite : 'コメント',
attribute_events_tab : 'イベント',
attribute_attrib_tab : '属性',
general_tab : '一般',
attrib_tab : '属性',
events_tab : 'イベント',
fieldset_general_tab : '基本設定',
fieldset_attrib_tab : 'エレメント 属性',
fieldset_events_tab : 'エレメント イベント',
title_ins_element : 'エレメント 挿入',
title_del_element : 'エレメント 削除',
title_acronym_element : '頭文字語要素',
title_abbr_element : '略語要素',
title_cite_element : '引用要素',
remove : '削除',
not_set : '--not set--',
insert_date : '現時刻挿入',
option_ltr : '左から右',
option_rtl : '右から左',
attribs_desc : '属性 挿入/編集',
attribs_title : '属性 挿入/編集'
});
